version: '3.8'

services:
  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: sanosysalvos
    volumes:
      - mongo_data:/data/db

  ms-gestion-mascotas:
    build: ./ms-gestion-mascotas
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  ms-geolocalizacion:
    build: ./ms-geolocalizacion
    ports:
      - "3002:3002"

  ms-motor-coincidencias:
    build: ./ms-motor-coincidencias
    ports:
      - "3003:3003"
    depends_on:
      - mongo

volumes:
  mongo_data: